#!/usr/bin/python3

# This prints a single string
print("Hello World")


# This can print many strings
print("""
What is your name
Where are you from
""")

# To combine two string
print("Hello " + "Uche")
